### ISSUE TITLE
Cannot find the UI of the plugin in MAYA

### ISSUE THREAD

**Issue by xiaojin2333** [timmwagener/tw_cloth_solver#2]
It looks such lovely in the demo. But when I downloaded it and compiled the cpp code, I couldn't find the UI as the video shows. How can I use it correctly. I can only find two commands called "vcsPositionConstraint" and "vcsPositionConstraintSphere".
I have tried the following steps. When I selected a plane in Maya2018 and inputted the command "vcsPositionConstraint", it showed "Plug outMesh not connected to anything. Continuing."

**Comment by timmwagener** [comment]
Hello @xiaojin2333 

the user interface is located in an `AE Template` _(Attribute Editor Template)_ mel script:
* [`AEverletClothSolverTemplate.mel`](https://github.com/timmwagener/tw_cloth_solver/blob/master/ae_template/AEverletClothSolverTemplate.mel)

For an example on how to set the solver up, please have a look at the scripts that I created for exactly that purpose during development:
* [Re-create and reload solver scene for Python solver blockout](https://github.com/timmwagener/tw_cloth_solver/blob/master/temp/twClothSolverIOPaperBlockoutTestFixture.py)
* [Re-create and reload solver scene for C++ solver implementation](https://github.com/timmwagener/tw_cloth_solver/blob/master/temp/twClothSolverTestFixture.py)

Please keep in mind that these solvers were developed around Maya 2012, and I haven't tested or updated them since for newer Maya releases. I cannot guarantee that they would compile or behave correctly for newer versions.

**Comment by xiaojin2333** [comment]
Thank you so much for your help. I have successfully loaded the plugin and found the UI elements. The plugin works well, and MAYA2018 can support it.
